
POST https://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "testuser15",
    "password": "Test123@"
}

###

POST https://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "",
    "password": "Test123@"
}

###







