services:
  back:
    container_name: back
    image: back
    build:
      context: ./back
      dockerfile: Dockerfile
    working_dir : /usr/src/app
    ports:
      - 3000:3000
    env_file: ../.env
    volumes: 
      - back_vol:/usr/src/app
    networks:
      - transcendence
    restart: unless-stopped 


  front:
    container_name: front
    image: front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      back:
        condition: service_started
    env_file: ../.env
    volumes: 
      - front_vol:/usr/src/app
    networks:
      - transcendence
    restart: unless-stopped

networks:
  transcendence:
    driver: bridge
    name: transcendence

volumes:
  back_vol: {}
  front_vol: {}